# Generated by Django 5.2.11 on 2026-04-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_goods_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="goods/"),
        ),
    ]
