# Generated by Django 6.0.5 on 2026-06-10 16:38

import django.db.models.deletion
import goods.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(default=goods.models.generate_order_no, max_length=20, unique=True, verbose_name='订单编号')),
                ('price', models.FloatField(verbose_name='成交价格')),
                ('status', models.IntegerField(choices=[(0, '待确认'), (1, '交易中'), (2, '已完成'), (3, '已取消')], db_index=True, default=0, verbose_name='状态')),
                ('cancel_reason', models.CharField(blank=True, max_length=200, verbose_name='取消原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='下单时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_orders', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL, verbose_name='取消人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='goods.goods', verbose_name='商品')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_orders', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
