# Generated by Django 6.0.6 on 2026-06-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_add_review_cart_announcement_reset_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='其他', help_text='可使用 Emoji 表情或图标类名', max_length=20, verbose_name='图标'),
        ),
    ]
